### ISSUE TITLE
Explain how to get new validators

### ISSUE THREAD

**Issue by micho** [shamirlabs/docs#18]
As somebody in touch with operators both on discord and privately, I see this question every single day.

Can we add it to the docs?

Also the Operator web UI has a similar issue: https://github.com/shamirlabs/diva-alpha-net/issues/33

<img width="587" alt="image" src="https://github.com/shamirlabs/docs/assets/323401/2bc24c49-a0aa-45bf-aa49-59322fbcc650">

![image](https://github.com/shamirlabs/docs/assets/323401/377f00c4-3ad6-4a1b-8b2f-67091842b8c4)

**Comment by micho** [comment]
I'll add more examples as I find them

<img width="588" alt="image" src="https://github.com/shamirlabs/docs/assets/323401/5e416afd-4095-415e-91d2-95ed74a9c812">

**Comment by pradavc** [comment]
Duplicated: https://github.com/shamirlabs/docs/issues/18

**Comment by micho** [comment]
Where is the new issue tracked? The last comment just self references this issue, link is wrong
