### ISSUE TITLE
Operator UI dashboard issue when swapping between WiFi and LAN

### ISSUE THREAD

**Issue by Gaiability** [shamirlabs/docs#4]
When changing the internet connection from WiFi over to LAN the UI loses connection to Node/Wallet.

Error message in Web browser:
on localhost/dashboard: 'Connected wallet is not the Diva operator of this node'. 
on xxx.xxx.x.xx/dashboard: The page is unable to connect

Other relevant info:
*The node is set up over WiFi
*Operating UI locally, eg not remote logged in
*The node is set to have a permanent IP from router, which is set up over Wifi
*Removing permanent IP, changing to other IP etc, does not resolve the problem.
*Is its still perfectly possible to stake from Operator wallet/address at: stake.diva.community, from the node computer, during error messages.

UI seems to be overriding the Wallet connection/Operator address in favor of IP address? of the node

**Comment by pradavc** [comment]
This is an unrelated error probably due to a network issue in your setup. I think you probably fixed it, so I will close this issue.
